### ISSUE TITLE
support Scala 2.12.0-M4

### ISSUE THREAD

**Issue by xuwei-k** [scala-js/scala-js-java-time#13]

**Comment by sjrd** [comment]
Good point. I published 0.1.0 for 2.12.0-M4 on Sonatype. Hang tight for the sync to Maven Central.

**Comment by xuwei-k** [comment]
Thanks! I confirmed.

http://repo1.maven.org/maven2/org/scala-js/scalajs-java-time_sjs0.6_2.12.0-M4/
