### ISSUE TITLE
Clarify goal of project and alternatives in README

### ISSUE THREAD

**Issue by chuwy** [scala-js/scala-js-java-time#26]
I think it could be useful to provide new users a little note that they currently can use https://github.com/cquiroz/scala-java-time as drop-in replacement for `java.time`, whereas this project intended to be **only** JS implementation.

I got this information from [this](https://github.com/scala-js/scala-js-java-time/issues/7) lengthy thread, but maybe I misenterpret something.

**Comment by rpiaggio** [comment]
If I may place a suggestion, it could also be mentioned that for a lightweight alternative, https://github.com/zoepepper/scalajs-jsjoda is also availbable.
