### ISSUE TITLE
Summarise what is and isn't available

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-java-time#6]
It would be very helpful to have a page or file that shows which parts of `java.time` have been implemented, and which parts haven't. Such information will be helpful for people to
- decide whether they can use this yet
- how much need be contributed to satisfy their desired use
- what can be contributed if someone's enthusiastic or bored.

**Comment by sjrd** [comment]
What about this "page": https://github.com/scala-js/scala-js-java-time/tree/master/src/main/scala/java/time ?
It's an honest question. What more do you need?

**Comment by japgolly** [comment]
At a class level, that's ok to show what's done but there isn't a list of what's _not_ done. I'm curious as to how much is actually done. Eg. 124/200 classes, or 1000/1300 methods. Something like that.

Also some of those classes when you peek through, are missing methods. If I ignore for a second to cost to setup it up, I think it'd be cool to have something like a list of classes in the Java API and along each, the percentage implemented here.

**Comment by sjrd** [comment]
Right. Yes, that would be useful, indeed.

**Comment by nicolasstucki** [comment]
I created  #7 which keeps track of all implemented classes and gives their percentage.

**Comment by japgolly** [comment]
Oh cool, thanks @nicolasstucki. Currently 24/69 then. That's a good start.
